config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'messages/create'
  get 'messages/show'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'

  get '/dashboard', to: 'pages#dashboard'
  resources :bookings, only: [:destroy]
  # root to: "equipment#index"
  resources :equipment do
    resources :bookings, only: [:new, :create, :update, :edit]
    # resources :reviews, only: [:create]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :equipment
  belongs_to :user
  has_one :message
  validates :start_date, :end_date, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  validates :title, :description, :price, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_and_category,
    against: [ :title, :category ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :bookings

end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :equipment
  has_many :incoming_bookings, through: :equipment, source: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :authenticate_user!

  def new
    @equipment = Equipment.find(params[:equipment_id])
    @booking = Booking.new
  end

  def create
    @equipment = Equipment.find(params[:equipment_id])
    @booking = Booking.new(booking_params)
    @booking.equipment = @equipment
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @bookings = Booking.find(params[:id])
    @equipment = @bookings.equipment
  end


  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

      def index
        if params[:query].present?
          @equipment = Equipment.search_by_title_and_category(params[:query])
        else
          @equipment = Equipment.all
        end
      end

      def show
        @booking = Booking.new
        @equipment = Equipment.find(params[:id])
      end

      def new
        @equipment = Equipment.new
      end

      def create
        @equipment = Equipment.new(equipment_params)
        @equipment.user = current_user
        if @equipment.save!
          redirect_to equipment_path(@equipment)
        else
          render :new
        end
      end
      



      def edit
        @equipment = Equipment.find(params[:id])
      end

      def update
        @equipment = Equipment.find(params[:id])
        @equipment.update(equipment_params)
        redirect_to equipment_path(@equipment)
      end

      def destroy
        @equipment = Equipment.find(params[:id])
        @equipment.destroy
        redirect_to dashboard_path
      end

      private

      def equipment_params
        params.require(:equipment).permit(:title, :category, :price, :description, :location, :rules, photos: [])
      end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
#   def new
#     @booking = Booking.find(params[:booking_id])
#     @message = Message.new
#   end

#   def create
#     @bookings = booking.find(params[:bookings_id])
#     @message = Message.new(message_params)
#     @booking.messages = @messages
#     @message.user = current_user
#     if @message.save
#       redirect_to dashboard_path
#     else
#       render :new
#     end
#   end

#   def show
#   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @equipment = current_user.equipment
    @bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
end

app/views/bookings/edit.html.erb
<div class="top-space"></div>
<div class="form-container" style="background-image: url(#);">
  <div class="child-create">
    <div class="banner-h1">
      <h1>Edit your booking</h1>
    </div>
      <%= simple_form_for([@equipment, @bookings]) do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit :submit  %>
      <% end %>
      <%= link_to "Back", dashboard_path %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="bg">

<div class="form-container" style="background-image: url(#);">
  <div class="child-create">
    <div class="banner-h1">
      <h1>Book the <%= @equipment.title %></h1>
    </div>
      <%= simple_form_for([@equipment, @booking]) do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit :submit  %>
      <% end %>
      <%= link_to "Back", equipment_path(@equipment) %>
  </div>
</div>





</div>

<p>This example creates a full page background image. Try to resize the browser window to see how it always will cover the full screen (when scrolled to top), and that it scales nicely on all screen sizes.</p>

app/views/equipment/edit.html.erb
<style>
        body{
           background-color: #fdffff;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='250' height='30' viewBox='0 0 1000 120'%3E%3Cg fill='none' stroke='%23ececec' stroke-width='10' %3E%3Cpath d='M-500 75c0 0 125-30 250-30S0 75 0 75s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 45c0 0 125-30 250-30S0 45 0 45s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 105c0 0 125-30 250-30S0 105 0 105s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 15c0 0 125-30 250-30S0 15 0 15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500-15c0 0 125-30 250-30S0-15 0-15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 135c0 0 125-30 250-30S0 135 0 135s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3C/g%3E%3C/svg%3E");
        }
    </style>

<div class="top-space"></div>

<div class="form-container" style="background-image: url(#);">
  <div class="child-create">
    <div class="banner-h1">
      <h1>Create <strong>your</strong> listing</h1>
    </div>
      <%= simple_form_for(@equipment) do |f| %>
        <%= f.input :title %>
        <%= f.input :price %>
        <%= f.input :category %>
        <%= f.input :description %>
        <%= f.input :rules %>
        <%= f.input :location %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit :submit  %>
      <% end %>
      <%= link_to "Return Home", root_path %>
  </div>
</div>

app/views/equipment/index.html.erb
<style>
        body{
           background-color: #fdffff;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='250' height='30' viewBox='0 0 1000 120'%3E%3Cg fill='none' stroke='%23ececec' stroke-width='10' %3E%3Cpath d='M-500 75c0 0 125-30 250-30S0 75 0 75s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 45c0 0 125-30 250-30S0 45 0 45s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 105c0 0 125-30 250-30S0 105 0 105s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 15c0 0 125-30 250-30S0 15 0 15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500-15c0 0 125-30 250-30S0-15 0-15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 135c0 0 125-30 250-30S0 135 0 135s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3C/g%3E%3C/svg%3E");
        }
    </style>



<div class="top-space"></div>
<div class="card-container backgroundpattern">
<% @equipment.each do |eq| %>

  <div class="card">
      <div class="equipment-card">
        <div class="card-image">
            <%= link_to cl_image_tag(eq.photos.first.key), equipment_path(eq)  %>
        </div>
      <div class="info">
        <div><p class="review"><i class="fas fa-star"></i><% star_rand_num = rand(4.0..5.0).round(1) %> <%= star_rand_num %><% rand_num = rand(10.0-500.0).round(2) %><div class="review_number">(<%= rand_num %>)</p></div>
      </div>
        <p class="title"><%= eq.title %></p>
        <p class="card_price">£<%= eq.price.round %></p>
      <%# <div class="book_now"> %>
        <%# <button class="card_button">Show me</button> %>

            <%# <button class="button"><%= link_to 'Show me', equipment_path(eq) %>
    <%# </div> %>
      </div>
    </div>
  </div>
<% end %>
</div>

 

app/views/equipment/new.html.erb
<style>
        body{
           background-color: #fdffff;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='250' height='30' viewBox='0 0 1000 120'%3E%3Cg fill='none' stroke='%23ececec' stroke-width='10' %3E%3Cpath d='M-500 75c0 0 125-30 250-30S0 75 0 75s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 45c0 0 125-30 250-30S0 45 0 45s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 105c0 0 125-30 250-30S0 105 0 105s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 15c0 0 125-30 250-30S0 15 0 15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500-15c0 0 125-30 250-30S0-15 0-15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 135c0 0 125-30 250-30S0 135 0 135s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3C/g%3E%3C/svg%3E");
        }
    </style>


<div class="top-space"></div>




<div class="bannerprofilenew" style="background-color:white">
</div>
<div class="top-textnew">
  <h1>List it on here</h1>
  <h2 class="top-h2new">Then get back out there.</h2>
</div>





  <div class="profile-container">
    <div class="card1new">

           <img class="mountain" src="https://i.guim.co.uk/img/media/6088d89032f8673c3473567a91157080840a7bb8/413_955_2808_1685/master/2808.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=412cc526a799b2d3fff991129cb8f030" />
     
   
        
    
    </div>

      <div class="card2new">
<div class="form-container" style="background-image: url(#);">
  <div class="child-create-new">
      <%= simple_form_for(@equipment) do |f| %>
        <%= f.input :title %>
        <%= f.input :price %>
        <%= f.input :category %>
        <%= f.input :description %>
        <%= f.input :rules %>
        <%= f.input :location %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit :submit %>
      <% end %>
      <%= link_to "Return Home", root_path %>
  </div>
</div>
    </div>
  </div>

app/views/equipment/show.html.erb
<style>
        body{
           background-color: #fdffff;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='250' height='30' viewBox='0 0 1000 120'%3E%3Cg fill='none' stroke='%23ececec' stroke-width='10' %3E%3Cpath d='M-500 75c0 0 125-30 250-30S0 75 0 75s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 45c0 0 125-30 250-30S0 45 0 45s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 105c0 0 125-30 250-30S0 105 0 105s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 15c0 0 125-30 250-30S0 15 0 15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500-15c0 0 125-30 250-30S0-15 0-15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 135c0 0 125-30 250-30S0 135 0 135s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3C/g%3E%3C/svg%3E");
        }
    </style>

<div class="top-space"></div>

</div>
<div class="top-text">
  <h1>Check it out,</h1>
  <h2 class="top-h2">You're really going to love this one.</h2>
</div>



<div class="booking_container">
 
  <div class="booking-card">










    
  </div>
</div>


<div class="show-container">
    <div class="card1show">
      <div class="cardbox1-leftshow">
   
      <h1><%= @equipment.title %></h1>
      <p class="card-product-desc"><%= @equipment.description %></p>
      <hr>
      <p class="card-product-label"><i class="far fa-calendar-alt"></i> Cancellation Policy</p>
      <p class="card-product-label-desc">Free cancellation up to 24 hours before booking.</p>
      <p class="card-product-label"><i class="fas fa-ruler"></i> Rules for Renting</p>
      <p class="card-product-label-desc"><%= @equipment.rules %></p>




      <div class="card-product-infos">
      <h2>£<%= @equipment.price.round %> per day</h2>
      <% if @equipment.user == current_user %>
        <button class="button-show" style="width: 75px;"><%= link_to ' Edit ',  edit_equipment_path(@equipment) %></button>
        <button class="button-show" style="width: 75px;"><%= link_to 'Remove',  equipment_path(@equipment), method: :delete,  data: { confirm: "Are you sure?" }  %></button>
        <button class="button-show" style="width: 75px;"><%= link_to 'Back',  request.referer.present? ? request.referer : default_path %></button>
      <% else %>
        <button class="button-show" style="width: 75px;"><%= link_to 'Back',  request.referer.present? ? request.referer : default_path %></button>
      <% end %>
    </div>




<div class="email" onclick="this.classList.add('expand')">
      <div class="from">
        <div class="from-contents">
          <div class="name">Book Now</div>
        </div>
      </div>
    <div class="to">
      <div class="to-contents">
        <div class="topbar">
          <div class="name-large">Book Now</div>
          <div class="x-touch" onclick="document.querySelector('.email').classList.remove('expand');event.stopPropagation();">
            <div class="x">
              <div class="line1"></div>
              <div class="line2"></div>
            </div>
          </div>
        </div>
        <div class="bottom">
          <div class="row">
            <%= simple_form_for([@equipment, @booking]) do |f| %>
            <%= f.input :start_date %>
            <%= f.input :end_date %> 
            <%= f.submit :submit %> 
          <% end %>
          </div>
          <div class="row">
            <svg class="medium" viewBox="0 0 24 24">
              <style type="text/css" id="style2">
                .st0{fill:#3DD87F;}
                .st1{fill:#FFFFFF;}
              </style>
              <g id="Page-1" transform="translate(0,1)">
                <g id="Monogram">
                </g>
              </g>
            </svg>
          </div>
        </div>
      </div>
    </div>







    </div>
    
  </div>
  </div>
      
      <div class="card2show">
             <div class="showphoto">
        <% @equipment.photos.each do |photo| %>
        <a href=""><%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %></a>
      <% end %>
    </div>
      </div>

    
  </div>
    </div>



<hr>
<div class="spacer">

    <h1>You may also like</h1>
    <ul>
      <li>
        <img src="https://www.cotswoldoutdoor.com/content/dam/uk/brands/1747.png" class="logo-img">
      </li>
      <li>
        <img img src="https://cdn.worldvectorlogo.com/logos/the-north-face-1.svg" class="logo-img">
      </li>
      <li>
        <img img src="https://cdn.worldvectorlogo.com/logos/arc-teryx.svg" class="logo-img">
      </li>
      <li>
        <img img src="https://cdn.worldvectorlogo.com/logos/patagonia.svg" class="logo-img">
      </li>
      <li>
        <img img src="https://www.cotswoldoutdoor.com/content/dam/uk/brands/1836.png" class="logo-img">
      </li>
    </ul>
    <h2>Find the kit to fuel your adventures.</h2>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/a71e945cdd.js" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <style>
        body{
           background-color: #fdffff;
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='250' height='30' viewBox='0 0 1000 120'%3E%3Cg fill='none' stroke='%23ececec' stroke-width='10' %3E%3Cpath d='M-500 75c0 0 125-30 250-30S0 75 0 75s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 45c0 0 125-30 250-30S0 45 0 45s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 105c0 0 125-30 250-30S0 105 0 105s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 15c0 0 125-30 250-30S0 15 0 15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500-15c0 0 125-30 250-30S0-15 0-15s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3Cpath d='M-500 135c0 0 125-30 250-30S0 135 0 135s125 30 250 30s250-30 250-30s125-30 250-30s250 30 250 30s125 30 250 30s250-30 250-30'/%3E%3C/g%3E%3C/svg%3E");
        }
    </style>

    <%= render 'shared/navbar'%>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
  <footer>
    <%= render 'shared/footer'%>
  </footer>
</html>

app/views/pages/dashboard.html.erb
<%time = current_user.created_at %>
<%time = time.strftime("%B %Y") %>
<div class="main-page">
</div>
<div class="top-text">
  <h1>Hi there,</h1>
  <h2 class="top-h2">We have a few things for you to look at.</h2>
</div>
</div>
  <div class="profile-container">
    <div class="card1" style="overflow-y: scroll;">
      <div class="cardbox1-left">
        <i class="far-icon fa-user-circle"></i>
        <h4 class="page-h2"><%= current_user.email%></h4>
        <p class="time">Joined <%= time %></p>
        <p>Change password here</p>
         
        <%= link_to "List new equipment", new_equipment_path, class: "btn btn-secondary" %>

      </div>
      <div class="cardbox1-right">
        <h3 class="right-page-h2">Listed Equipment</h3>
        <div class="photosbox">
          <% if @equipment %>
            <% @equipment.each do |eq| %>
              <div class="profilephotos">
              <%= link_to cl_image_tag(eq.photos.first.key), equipment_path(eq) %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

      <div class="card2">
        <h3 class="page-h2">EquipRent Travel</h2>
        <p class="travel-text">A Randonnée is the cycling holiday of a lifetime. These point-to-point adventures cover cycling’s most celebrated landscapes, challenging and inspiring riders in equal measure.</p>
        <p class="travel-text">Ex Duris Gloria</p>
        <a class="btn btn-secondary" href="">Learn more</a>
        <img src="https://cdn.iconscout.com/icon/free/png-256/mountain-2125950-1789239.png">
    </div>
  </div>



  <div class="profile-container">  
      <div class="card4">
              <img class="equipclub" src="https://i.imgur.com/Aa7W35W.png">
        <h3 class="page-h2">Equip Club</h2>
        <p class="travel-text">The Equip Club is a global community of passionate, active adventurists with exclusive access to our most sought after products, experiences and offers.
        A global network of more than 13,000 like-minded people and travel leaders connected by an easy-to-use app with hundreds of routes.</p>
        <a class="btn btn-secondary" href="">Learn more</a>
    </div>
  <div class="card5">
    <h3 class="page-h2">Bookings from you</h3>
      <% @bookings.each do |booking| %>
        <div class="bookingtext">
          You booked this <%= booking.equipment.title.downcase %>
          from <%= booking.start_date %>
          to <%= booking.end_date %>
        </div>
        <%= link_to 'Edit booking',  edit_equipment_booking_path(booking.equipment, booking), class: "btn btn-secondary"%>
        <%= link_to 'Cancel booking',  booking_path(booking), method: :delete,  data: { confirm: "Are you sure?" }, class: "btn btn-secondary"%>
      <% end %>
      
      <h3 class="page-h2">Bookings for you</h3>
    
      <h1><% current_user.incoming_bookings.each do |booking|%></h1>
     <div>
      Your <%= booking.equipment.title %> has beeen booked
      From <%= booking.start_date %>
      To <%= booking.end_date %>
     </div>
      <% end %>
  </div>
    </div>

app/views/shared/_footer.html.erb
<div class="top-space"></div>

<div class="footer-photo">
<img class="footer-img" src="https://i.imgur.com/KPYgU2N.png" alt="#">
</div>
<div class="footer">
<h3>Our Mission</h3>
<div class="mission">
We to eliminate the unnecessary waste caused by single use outdoor equipment. We want the circular economy to grow. But most of all we want you to get out there and hit the trails, waves, or walls.
<hr>
© 2020 EquipRent, Ltd
</div>
<div class="socials">
<i class="fab fa-instagram"></i>
<i class="fab fa-facebook"></i>
<i class="fab fa-twitter"></i>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="top-space"></div>
<div class="navbar navbar-expand-md navbar-light navbar-lewagon <%= yield(:nav_style) %>" id="test" >

<div id="cflink" href="<%= link_to root_path %>">
  <a href="/"><img class="top" src="https://i.imgur.com/U2Tx2Pj.png"/></a>
</div>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <%if user_signed_in?%>

        <div class="links-navbar">
          <strong><%= link_to "Browse", equipment_index_path %></strong>
                  <%= link_to "Dashboard", dashboard_path %>
                  <%= link_to "Help", root_path %>
            <div class="dropdown">
              <button class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i>
              </button>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Add Equipment", new_equipment_path, class: "dropdown-item" %>
                <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item" %>
              </div>
            </div>
        </div>

      <% else %>

        <div class="links-navbar">
          <strong><%= link_to "Browse", equipment_index_path %></strong>
                <%= link_to "Help", root_path %>
            <div class="dropdown">
              <button class="btn btn-secondary" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user"></i>
              </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item"  %>
              <%= link_to "Login", user_session_path, class: "dropdown-item"  %>
            </div>
            </div>
        </div>

      <% end %>

    </ul>
  </div>
</div>